#!/bin/sh

# Copyright © 2013 Alex Kost

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#### HELP MESSAGE ##############################################
hlp='Usage: clock
Start "osd_clock" or kill it if already running.'

if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    echo "$hlp"
    exit 0
fi
################################################################

clock_proc=$(pgrep '^osd_clock$')
if [ -z $clock_proc ]; then
    osd_clock --center --middle -i4 -d5 -s4 -F '%H:%M' -c '#BFBF00' \
              -f "-*-ubuntu-bold-r-normal-*-*-3800-*-*-p-*-*"
else
    kill $clock_proc
fi
