#!/bin/sh

INI=$HOME/src/conkeror/application.ini

# Use icecat on GuixSD.
if [ -d "/run/current-system" ]; then
    PROG='icecat --app'
else
    # PROG='xulrunner'
    PROG='firefox --app'
fi

$PROG $INI "$@" &> /dev/null
