#!/bin/sh

# Copyright © 2014 Alex Kost

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Idea is taken from <https://wiki.archlinux.org/index.php/DPMS>.

usage () {
    echo 'Usage: monitor blank|standby|suspend|off|on
"monitor blank" is the same as "xset s activate".
Other keys are equivalents of "xset dmps force …".'
}

case "$1" in
    blank)
        sleep 1
        xset s activate
        ;;
    standby | suspend | off | on)
        sleep 1
        xset dpms force $1
        ;;
    *)
        usage
        ;;
esac
