#!/bin/sh

usage () {
    echo 'Usage: stumpwm-cmd COMMAND [ARGS ...]
Run StumpWM COMMAND with ARGS e.g.:

  stumpwm-cmd echo hello'
}

case "$1" in
    "" | -h | --help)
        usage
        exit 0 ;;
    *)
        xprop -root -f STUMPWM_COMMAND 8u -set STUMPWM_COMMAND "$*"
        ;;
esac

